name: hrtf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.0=py37_0
  - astor=0.7.1=py_0
  - attrs=19.1.0=py_0
  - audioread=2.1.6=py37_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - bzip2=1.0.8=h516909a_1
  - c-ares=1.15.0=h516909a_1001
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.9.11=py37_0
  - cffi=1.12.3=py37h8022711_0
  - cudatoolkit=10.1.168=0
  - cudnn=7.6.0=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py_1
  - dbus=1.13.6=he372182_0
  - decorator=4.4.0=py_0
  - defusedxml=0.5.0=py_1
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1003
  - ffmpeg=4.2=h167e202_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h516909a_1002
  - gast=0.3.2=py_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - google-pasta=0.1.7=py_0
  - graphite2=1.3.13=hf484d3e_1000
  - graphviz=2.40.1=h0f2764d_1
  - grpcio=1.23.0=py37he9ae1f9_0
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.10.0=nompi_py37h513d04c_100
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1103
  - icu=64.2=he1b5a44_1
  - ipykernel=5.1.2=py37h5ca1d4c_0
  - ipython=7.8.0=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.1=py37_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jpeg=9c=h14c3975_1001
  - json5=0.8.5=py_0
  - jsonschema=3.0.2=py37_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.4.0=py_0
  - jupyterlab=1.1.4=py_0
  - jupyterlab_server=1.0.6=py_0
  - keras-applications=1.0.8=py_1
  - keras-base=2.2.4=py37_0
  - keras-gpu=2.2.4=0
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - lame=3.100=h14c3975_1001
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libflac=1.3.1=hf484d3e_1002
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - libogg=1.3.2=h14c3975_1001
  - libopenblas=0.3.7=h6e990d7_1
  - libpng=1.6.37=hed695b0_0
  - libprotobuf=3.9.1=h8b12597_0
  - librosa=0.7.0=py_0
  - libsndfile=1.0.28=hf484d3e_1000
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h57b8799_1003
  - libtool=2.4.6=h14c3975_1002
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.30.1=h516909a_0
  - libvorbis=1.3.5=h14c3975_1001
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hee79883_5
  - llvmlite=0.29.0=py37hfd453ef_1
  - lz4-c=1.8.3=he1b5a44_1001
  - markdown=3.1.1=py_0
  - markupsafe=1.1.1=py37h14c3975_0
  - matplotlib=3.1.1=py37_1
  - matplotlib-base=3.1.1=py37he7580a8_1
  - mistune=0.8.4=py37h14c3975_1000
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - nodejs=12.8.1=h10a4023_0
  - notebook=6.0.1=py37_0
  - numba=0.45.1=py37hb3f55d8_0
  - numpy=1.17.2=py37h95a1406_0
  - olefile=0.46=py_0
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1c=h516909a_0
  - pandas=0.25.1=py37hb3f55d8_0
  - pandoc=2.7.3=0
  - pandocfilters=1.4.2=py_1
  - pango=1.42.4=ha030887_1
  - parso=0.5.1=py_0
  - patsy=0.5.1=py_0
  - pcre=8.41=hf484d3e_1003
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=6.1.0=py37h6b7be26_1
  - pip=19.2.3=py37_0
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.9=py_0
  - protobuf=3.9.1=py37he1b5a44_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.19=py37_1
  - pydot=1.4.1=py37_1001
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pyrsistent=0.15.4=py37h516909a_0
  - pysoundfile=0.10.2=py_1001
  - python=3.7.3=h33d41f4_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.2=py_0
  - pyyaml=5.1.2=py37h516909a_0
  - pyzmq=18.1.0=py37h1768529_0
  - qt=5.9.7=h0c104cb_3
  - readline=8.0=hf8c457e_0
  - resampy=0.2.2=py_0
  - scikit-learn=0.21.3=py37hcdab131_0
  - scipy=1.3.1=py37h921218d_2
  - seaborn=0.9.0=py_1
  - send2trash=1.5.0=py_0
  - setuptools=41.2.0=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.29.0=hcee41ef_1
  - statsmodels=0.10.1=py37hc1659b7_0
  - tensorboard=1.14.0=py37_0
  - tensorflow=1.14.0=gpu_py37h74c33d7_0
  - tensorflow-base=1.14.0=gpu_py37he45bfe2_0
  - tensorflow-estimator=1.14.0=py37h5ca1d4c_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py_2
  - terminado=0.8.2=py37_0
  - testpath=0.4.2=py_1001
  - tk=8.6.9=hed695b0_1003
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.2=py37_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxpm=3.5.12=h516909a_1002
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - yaml=0.1.7=h14c3975_1001
  - zeromq=4.3.2=he1b5a44_2
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.0=h3b9ef0a_0
  - pip:
    - astropy==3.2.2
    - cftime==1.0.3.4
    - keras-tqdm==2.0.1
    - netcdf4==1.5.2
    - pyshtools==4.5
    - sofasonix==1.0.6
    - xarray==0.13.0
prefix: /home/rmicci18/miniconda3/envs/hrtf

